apiVersion: v1
kind: Service
metadata:
  name: checkout-service-app
spec:
  selector:
    app.kubernetes.io/name: checkout-service-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080