apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
spec:
  destination:
    name: ''
    namespace: apps
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/auth-service
    repoURL: 'https://github.com/karlo235/DHBW-DevOps'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true